#
#   Copyright 2020 binx.io B.V.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ScheduledEvent:
    Type: String
    AllowedValues:
      - ENABLED
      - DISABLED
    Default: DISABLED
Resources:
  GitRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: aws-account-destroyer
      Triggers:
        - Name: BuildTrigger
          DestinationArn: !GetAtt 'BuildTrigger.Arn'
          Branches:
            - master
          Events:
            - updateReference
          CustomData: aws-account-destroyer

  Project:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: aws-account-destroyer
      Description: 'Destroy everything in your AWS Account'
      ServiceRole: !Ref 'ProjectRole'
      TimeoutInMinutes: 180
      Artifacts:
        Type: no_artifacts
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
        PrivilegedMode: true

      Source:
        Type: CODECOMMIT
        Location: !GetAtt 'GitRepository.CloneUrlHttp'
        BuildSpec: deploy.yaml
        GitCloneDepth: 0

  BuildTrigger:
    Type: AWS::Lambda::Function
    Properties:
      Description: trigger codebuild on commit
      Handler: index.handler
      Runtime: python3.7
      Role: !GetAtt 'BuildTriggerRole.Arn'
      FunctionName: aws-account-destroyer
      Code:
        ZipFile: |
          import boto3

          def handler(event, context):
            print('Starting a new build ...')
            cb = boto3.client('codebuild')
            build = {
              'projectName': event['Records'][0]['customData'],
              'sourceVersion': event['Records'][0]['codecommit']['references'][0]['commit']
            }
            print('Starting build for project {0} from commit ID {1}'.format(build['projectName'], build['sourceVersion']))
            cb.start_build(**build)

  BuildTriggerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref 'BuildTrigger'
      Principal: codecommit.amazonaws.com
      SourceArn: !GetAtt 'GitRepository.Arn'

  AWSAccountDestroyRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Destroy AWS Account resources daily
      Name: aws-account-destroyer
      ScheduleExpression: cron(0 23 * * ? *)
      State: !Ref ScheduledEvent
      Targets:
        - Id: aws-account-destroyer
          RoleArn: !GetAtt 'EventTriggerRole.Arn'
          Input: |
            {"buildspecOverride": "destroy.yaml"}
          Arn: !GetAtt Project.Arn

  EventTriggerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: aws-account-destroyer-event-trigger
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
            Condition: {}
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess

  BuildTriggerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: aws-account-destroyer-build-trigger
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
            Condition: {}
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess

  ProjectRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: aws-account-destroyer
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: codebuild.amazonaws.com
            Condition: {}
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
